{{- if and .values.bestpractices.enabled (dig "bestpractices" "disallowdefaultnamespace" "enabled" true (merge .values)) }}
apiversion: policies.kyverno.io/v1alpha1
kind: validatingpolicy
metadata:
  name: disallow-default-namespace
  annotations:
    policies.kyverno.io/title: disallow default namespace in vpol
    policies.kyverno.io/minversion: 1.14.0
    policies.kyverno.io/category: multi-tenancy in vpol
    kyverno.io/kubernetes-version: "1.30"
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: pod
    policies.kyverno.io/description: kubernetes namespaces are an optional feature that provide a way to segment and isolate cluster resources across multiple applications and users. as a best practice, workloads should be isolated with namespaces. namespaces should be required and the default (empty) namespace should not be used. this policy validates that pods specify a namespace name other than `default`. rule auto-generation is disabled here due to pod controllers need to specify the `namespace` field under the top-level `metadata` object and not at the pod template level.
spec:
  failurepolicy: {{ dig "bestpractices" "disallowdefaultnamespace" "webhookfailurepolicy" "fail" (merge .values) }}
  webhookconfiguration:
    timeoutseconds: 30
  {{- if dig "bestpractices" "disallowdefaultnamespace" "enablebackgroundscanning" true (merge .values) }}
  evaluation:
    background:
      enabled: true
  {{- end }}


  validationactions:
    - audit
  matchconstraints:
    resourcerules:
      # kyverno currently has a autogen rule turned on, meaning that it auto generates the rules for
      # the other kinds like: jobs, daemonsets, statefulsets and deployments
      # todo: check if desired, currently simpler implementation
      - apigroups:
          - ""
        apiversions:
          - v1
        operations:
          - create
          - update
        resources:
          - pods

  validations:
    - expression: object.metadata.namespace != 'default'
      message: using 'default' namespace is not allowed.

{{- end}}
