---
namespace: {}
policy-reporter:
  logging:
    encoding: json
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
  # We explicitly remove all filters because we want a complete dashboard
  sourceFilters: []
  plugin:
    trivy:
      logging:
        encoding: json
    kyverno:
      logging:
        encoding: json
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
  ui:
    logging:
      encoding: json
    enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
