---
metallb:
  controller:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
  speaker:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    frr:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
    reloader:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
    frrMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 100Mi
  prometheus:
    # kube-prometheus-stack binds prometheus to a ClusterRole with the appopriate permissions already
    # Setting it to true which is the default would not enable something new here
    # Re-enable (and set serviceAccount/namespace) only if Prometheus loses cluster discover e.g metallb showing zero targets
    rbacPrometheus: false
    serviceMonitor:
      enabled: true
  frr-k8s:
    prometheus:
      serviceMonitor:
        enabled: true
nodeSelectors: {}
namespace: {}
